--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/xBeastMode/WorldInventory
build-by-default: true
branches:
- master
projects:
  WorldInventory:
    path: ""
    icon: "icon.png"
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.1.1
...
