on: [push]

name: Upload Release Asset

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[Build]')"
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PHP Binary
        run: wget https://jenkins.pmmp.io/job/PHP-8.1-Aggregate/lastSuccessfulBuild/artifact/PHP-8.1-Linux-x86_64.tar.gz && tar xvf PHP-8.1-Linux-x86_64.tar.gz
      - name: Install Composer
        run: wget https://getcomposer.org/composer-stable.phar -O ./bin/composer.phar
      - name: Install Composer Dependencies
        run: ./bin/php7/bin/php ./bin/composer.phar install --no-interaction
      - name: Download Phar Console Script
        run: wget https://raw.githubusercontent.com/pmmp/DevTools/master/src/ConsoleScript.php -O ./bin/ConsoleScript.php
      - name: Create Phar
        run: |
          echo Building...
          chmod +x ./bin/ConsoleScript.php
          ./bin/php7/bin/php -dphar.readonly=0 ./bin/ConsoleScript.php --make "resources,src,vendor,plugin.yml" --out WorldInventory.phar
          echo Build completed!
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
      - name: Upload Phar
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./WorldInventory.phar
          asset_name: WorldInventory.phar
          asset_content_type: application/phar