name: PHPStan CI

on: [push, pull_request, workflow_dispatch]

jobs:
  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install PHP Binary
        run: wget https://jenkins.pmmp.io/job/PHP-8.1-Aggregate/lastSuccessfulBuild/artifact/PHP-8.1-Linux-x86_64.tar.gz && tar xvf PHP-8.1-Linux-x86_64.tar.gz
      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php
      - name: Install Composer Dependencies
        run: ./bin/php7/bin/php composer.phar install --no-interaction
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --level=9 --no-progress --memory-limit=2G ./src